// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_Lye9Pz1jaWsdOV5R98ov1HkFKBKOf4',
    appId: '1:524586578075:android:03e03bc2206e0c064ed63e',
    messagingSenderId: '524586578075',
    projectId: 'fcmnotifications-d4128',
    storageBucket: 'fcmnotifications-d4128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLmdkhuSu9RhQP8mrIPvasrfefpf1Duuc',
    appId: '1:524586578075:ios:7969bc5b5f8d317b4ed63e',
    messagingSenderId: '524586578075',
    projectId: 'fcmnotifications-d4128',
    storageBucket: 'fcmnotifications-d4128.firebasestorage.app',
    iosBundleId: 'com.example.fcmNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBtyPNYWshq9UrXommxHoECGz3p4qhLm8',
    appId: '1:524586578075:web:362ba1ddd98c08c24ed63e',
    messagingSenderId: '524586578075',
    projectId: 'fcmnotifications-d4128',
    authDomain: 'fcmnotifications-d4128.firebaseapp.com',
    storageBucket: 'fcmnotifications-d4128.firebasestorage.app',
  );
}
